// DO NOT EDIT THIS FILE.
// This file is part of the Jax Framework.
// If you edit this file, your changes will be lost when framework updates are applied.

// Copyright (c) 2010-2011 Ronald B. Cemer
// All rights reserved.
// This software is released under the BSD license.
// Please see the accompanying LICENSE.txt for details.

function getBaseURL() {
	var url = window.location.href;
	var idx1 = url.indexOf('?'), idx2 = url.indexOf('#');
	var idx = ((idx1 >= 0) && (idx2 >= 0)) ? Math.min(idx1, idx2) : ((idx1 >= 0) ? idx1 : idx2);
	if (idx >= 0) url = url.substring(0, idx);
	return url;
}
