// DO NOT EDIT THIS FILE.
// This file is part of the Jax Framework.
// If you edit this file, your changes will be lost when framework updates are applied.

// Copyright (c) 2010-2011 Ronald B. Cemer
// All rights reserved.
// This software is released under the BSD license.
// Please see the accompanying LICENSE.txt for details.

var htmlencodediv = null;
function htmlencode(text) {
	if (htmlencodediv == null) htmlencodediv = $('<div/>');
	htmlencodediv.text(text);
	return htmlencodediv.html();
}
