// DO NOT EDIT THIS FILE.
// This file is part of the Jax Framework.
// If you edit this file, your changes will be lost when framework updates are applied.

// Copyright (c) 2010-2011 Ronald B. Cemer
// All rights reserved.
// This software is released under the BSD license.
// Please see the accompanying LICENSE.txt for details.

// Toggle visibility of an element.
// If a second argument is specified, it should be true to make visible; false to hide.
function toggleElementVisible(elementId) {
	var show = (arguments.length >= 2) ?
		arguments[1] :
		(($('#'+elementId).css('display') == 'block') ? false : true);
	if (show) {
		$('#'+elementId).show('fast');
	} else {
		$('#'+elementId).hide('fast');
		// This is needed to make the element hide even when it's not currently under
		// a visible container element, such as just before displaying an input form.
		$('#'+elementId).css('display', 'none');
	}
}
